"""Small, persistent desktop localization and first-run preference store."""

from __future__ import annotations

import json
import os
import secrets
from pathlib import Path
from typing import Any, Mapping


UI_PREFERENCES_SCHEMA = "peerbridge.ui-preferences.v1"
SUPPORTED_LOCALES = ("zh-Hant", "zh-Hans", "en")
LOCALE_LABELS = {
    "zh-Hant": "繁體中文",
    "zh-Hans": "简体中文",
    "en": "English",
}
LABEL_LOCALES = {label: locale for locale, label in LOCALE_LABELS.items()}


class LocalizationError(ValueError):
    """Desktop language preferences or a catalog lookup are invalid."""


_CATALOG: dict[str, dict[str, str]] = {
    "zh-Hant": {
        "nav.chat": "01  對話",
        "nav.work": "02  工作板",
        "nav.review": "03  互評",
        "nav.change": "04  變更",
        "nav.audit": "05  審計",
        "nav.connect": "06  接入",
        "nav.memory": "07  記憶",
        "nav.feedback": "08  意見回饋",
        "nav.usage": "09  使用量",
        "nav.announcement": "10  公告",
        "sidebar.agent_library": "全域智能體庫 // 智能體 != 模型",
        "sidebar.version": "唯讀檢視＋MCP 傳送 // v{version}",
        "sidebar.library_none": "全域智能體庫 // 未選取",
        "sidebar.library_selected": "全域智能體庫 // {agent}",
        "sidebar.library_empty": "全域智能體庫為空",
        "sidebar.online": "在線",
        "sidebar.rooms": "房間",
        "sidebar.messages": "訊息",
        "sidebar.memory": "記憶",
        "sidebar.dispatch": "派送",
        "sidebar.open_calls": "待處理呼叫",
        "sidebar.active": "進行中",
        "sidebar.audit": "審計",
        "sidebar.sync": "同步",
        "sidebar.dispatch_running": "執行",
        "sidebar.dispatch_retry": "重試",
        "sidebar.dispatch_failed": "失敗",
        "sidebar.dispatch_completed": "完成",
        "sidebar.database_error": "資料庫錯誤",
        "page.chat": "對話",
        "page.work": "工作板",
        "page.review": "互評",
        "page.change": "變更",
        "page.audit": "審計",
        "page.connect": "安全接入",
        "page.memory": "共享記憶",
        "page.feedback": "意見回饋",
        "page.usage": "Token 使用量",
        "page.announcement": "公告",
        "usage.total_tokens": "累計 Token",
        "usage.input_tokens": "輸入 Token",
        "usage.output_tokens": "輸出 Token",
        "usage.coverage": "Token 覆蓋",
        "usage.dispatches": "完成／失敗",
        "usage.daily": "近 30 日 Token",
        "usage.platforms": "按供應商拆分",
        "usage.today": "今日 Token",
        "usage.models": "模型使用量",
        "usage.provider": "供應商",
        "usage.model": "模型",
        "usage.agent": "智能體",
        "usage.calls": "呼叫",
        "usage.reported": "已回報",
        "usage.input": "輸入",
        "usage.output": "輸出",
        "usage.cached_input": "快取輸入",
        "usage.reasoning": "推理",
        "usage.total": "合計",
        "usage.calls_no_tokens": "呼叫次數（未提供 Token）",
        "usage.provider_reported_tokens": "供應商回報 Token",
        "usage.unavailable": "未提供",
        "usage.partial": "部分回報",
        "usage.derived_total": "輸入加輸出推算合計",
        "usage.no_data": "尚無供應商回報的 Token 數據",
        "usage.note": "只顯示供應商真實回報的 Token；未提供的執行不會以字數估算。",
        "toolbar.search": "搜尋",
        "toolbar.pause": "|| 暫停",
        "toolbar.refresh": ">> 刷新",
        "toolbar.refreshing": "正在刷新...",
        "toolbar.refreshed": "已刷新 {time}",
        "toolbar.refresh_failed": "刷新失敗",
        "toolbar.help": "? 教學",
        "toolbar.announcements": "公告",
        "toolbar.announcements_unread": "公告 ({count})",
        "toolbar.updates": "檢查更新",
        "toolbar.language": "語言",
        "chat.attach": "+ 附件",
        "chat.clear_attachments": "清除附件",
        "chat.no_attachments": "未附加檔案",
        "chat.attachments_selected": "已選取 {count} 個附件；送出後以內容 SHA 安全命名。",
        "chat.attachment_note": "附件會以雜湊副本保存；模型能否直接理解圖片取決於供應商。",
        "chat.to": "收件者",
        "chat.priority": "優先級",
        "chat.priority.low": "低",
        "chat.priority.normal": "一般",
        "chat.priority.high": "高",
        "chat.priority.critical": "緊急",
        "chat.task": "任務",
        "chat.provider": "供應商",
        "chat.model": "模型",
        "chat.reasoning": "推理強度",
        "chat.subject": "主旨",
        "chat.new_room": "+ 新房間",
        "chat.join_control": "+ 加入控制",
        "chat.older": "< 較舊",
        "chat.latest": "最新 >",
        "chat.focus": "⛶ 全屏對話",
        "chat.exit_focus": "退出全屏",
        "chat.auto": "自動",
        "chat.mode.off": "關閉自動回覆",
        "chat.mode.once": "每個 Agent 回覆一輪",
        "chat.mode.discussion": "有限持續討論",
        "chat.rounds": "回合",
        "chat.messages": "訊息",
        "chat.stagnation": "停滯",
        "chat.apply": "套用",
        "chat.pause": "暫停",
        "chat.resume": "恢復",
        "chat.continue": "繼續",
        "chat.stop": "停止",
        "chat.room_seats": "房間席位",
        "chat.apply_seat": "+ 套用席位",
        "chat.remove_seat": "- 移除",
        "chat.manage_providers": "06 接入",
        "chat.send": ">> MCP 送出",
        "chat.message_hint": "Enter 送出 / Shift+Enter 換行",
        "chat.join_to_send": "你尚未加入此房間。請按「+ 加入控制」加入 human-operator 席位後再送出。",
        "chat.seat_hint": "選擇 Global Agent，再加入目前房間。",
        "chat.recipient.all": "全體 Agent (*)",
        "chat.route.direct": "Agent 預設 Route",
        "chat.route.broadcast": "房間席位已指定的模型",
        "chat.route.unregistered": "未登記來源（到 06 接入）",
        "chat.route_unique_required": "找不到唯一 Route；請重新選擇 Provider、模型與思考強度。",
        "chat.required_fields": "需要任務、主旨和訊息內容。",
        "chat.broadcast_missing_routes": "全體送出已停止：請先用 Agent 方格右側 ▼ 設定模型：{agents}",
        "chat.routed_broadcast_forbidden": "指定模型路由時必須選擇一個 Agent，不能廣播。",
        "chat.sending": "正透過 MCP stdio 寫入 {room} 的 SHA 綁定訊息...",
        "chat.send_failed": "發送失敗：{error}",
        "chat.sent": "{fanout}已送出至 {room} // SHA {sha} // {created}",
        "chat.fanout": "分派至 {count} 個 Agent // ",
        "chat.secret_rejected": "訊息看似包含 API Key 或 Token；為避免寫入審計庫，已拒絕發送。",
        "chat.body_too_long": "訊息超過 20,000 字元上限。",
        "chat.model.default": "供應商預設模型",
        "chat.reasoning.default": "供應商預設推理",
        "chat.lobby_hint": "Lobby 預設包含 Global Library Agent；拖出會建立可稽核的接收停用記錄。",
        "seat.no_connections": "{agent} 沒有可安全查詢的 Provider connection。",
        "seat.refreshing": "正在安全重新查詢 {agent} 的 Provider 模型清單...",
        "seat.selected": "{agent} 已選取；可修改 Provider、模型及推理強度後套用。",
        "seat.no_route": "{agent} 尚未登記可執行模型 Route。",
        "seat.multiple_providers": "{agent} 有多個 Provider；請先選擇。",
        "seat.select_model": "請選擇此 Agent 要使用的模型。",
        "seat.select_reasoning": "請選擇此模型的推理強度。",
        "seat.advertised": "API 已列出 {model}；按「套用席位」會再次核驗並建立 Route。",
        "seat.configured": "設定完成：{agent} → {model} / {reasoning}；按「套用席位」。",
        "seat.route_unique": "找不到唯一 Route；請重新選擇 Provider、模型與推理強度。",
        "seat.drop_agent_cancelled": "拖放已取消 // Agent 仍留在全域智能體庫，未建立房間席位。",
        "seat.drop_seat_cancelled": "拖放已取消 // 席位仍在房間；拖到左側全域智能體庫才會移除。",
        "seat.menu_current": "目前：{route}",
        "seat.menu_options": "可選 {models} 個模型 / {providers} 個 Provider",
        "seat.menu_advertised": " · API 已列出，點選後核驗",
        "seat.menu_no_route": "沒有可用 Route，請先到 06 接入",
        "seat.menu_refresh": "重新同步 Provider 模型清單",
        "seat.menu_remove": "移除此房間席位（保留歷史）",
        "seat.select_agent": "請先從全域智能體庫選擇 Agent。",
        "seat.incomplete": "尚未完成模型設定：請選擇 Provider、模型與推理強度。",
        "seat.missing_provider_identity": "未登記模型缺少 Provider identity；已停止套用。",
        "seat.no_revalidatable_connection": "找不到唯一、可安全重新驗證的 Provider connection。",
        "seat.provider_model_removed": "Provider 已不再列出所選模型；沒有建立 Route。",
        "seat.codex_identity_incomplete": "官方 Codex 模型 identity 不完整；已停止套用。",
        "seat.codex_model_removed": "Codex 已不再列出所選模型；沒有建立 Route。",
        "seat.codex_reasoning_removed": "所選推理強度不再受這個 Codex 模型支援。",
        "seat.select_remove": "請先選擇要移除的房間席位。",
        "seat.keep_control": "控制者席位必須保留，以維持房間操作權。",
        "seat.confirm_remove": "停止 {agent} 接收 {room} 的新訊息？\n既有訊息與歷史不會刪除。",
        "seat.lobby_bound_only": "Lobby 只喚醒已綁定 Route 的席位；在 Agent 方格 ▼ 選擇模型。",
        "provider.display_name_required": "DISPLAY NAME 不可留空。",
        "provider.class_invalid": "CLASS 必須是 official、relay 或 local。",
        "provider.endpoint_required": "ENDPOINT 不可留空。",
        "provider.local_loopback_only": "LOCAL Provider 只允許 loopback endpoint。",
        "provider.api_key_required": "OFFICIAL 與 RELAY Provider 必須提供 API KEY。",
        "provider.show_api_key": "顯示",
        "provider.hide_api_key": "隱藏",
        "provider.saving": "正在安全儲存 Provider descriptor，然後經 MCP 登記 SHA 綁定 metadata...",
        "provider.save_failed": "Provider 驗證或 MCP 登記未完成；輸入已清空；credential descriptor 可能已保存。{error}",
        "provider.test_route_missing": "找不到唯一、已啟用的 Route；請先完成登記。",
        "provider.test_confirm_title": "確認一次真實 Provider 測試",
        "provider.test_confirm_body": "將向 {agent} / {model} 發送一次最小推理請求。這可能消耗額度；只有真實回覆才能驗證登入、權限與餘額。繼續？",
        "provider.test_queue_failed": "Provider 實測未能排入佇列：{error}",
        "provider.test_queued": "實測已排入 Lobby：{task} // SHA {sha}。聊天記錄會顯示回覆或明確終止原因。",
        "agent_install.heading": " 00  Agent 終端與 ACP 互通層 // 安裝與更新 ",
        "agent_install.intro": "官方 Agent 與社群互通層會分開標示；只執行固定、經審核的套件，不接受聊天室、Provider 或使用者提供的安裝網址／命令。安裝不包含登入、訂閱或模型額度。",
        "agent_install.detect_all": ">> 重新檢測全部終端",
        "agent_install.install": "安裝",
        "agent_install.update": "更新",
        "agent_install.open_guide": "官方指南",
        "agent_install.docs": "說明",
        "agent_install.detecting": "正在檢測…",
        "agent_install.detect_failed": "終端檢測失敗；未執行任何安裝。",
        "agent_install.installed": "已安裝 // {version}",
        "agent_install.not_installed": "未安裝。",
        "agent_install.version_unknown": "版本未回報",
        "agent_install.manual_only": "已開啟官方指南；Windows 自動安裝來源尚未通過供應商驗證。",
        "agent_install.confirm_title": "確認官方終端安裝",
        "agent_install.confirm_body": "即將在可見終端用官方套件管理器安裝／更新 {name}：\n\n{package}\n\nPeerBridge 不會替你登入，也不能提供訂閱或模型額度。繼續？",
        "agent_install.launch_failed": "無法啟動官方套件管理器：{error}",
        "agent_install.running": "安裝／更新正在獨立終端執行；完成前請勿關閉該終端。",
        "agent_install.completed": "套件管理器已完成；正在重新檢測。",
        "agent_install.failed": "套件管理器以代碼 {code} 結束；請查看可見終端的原始錯誤。",
        "agent_install.note.codex": "安裝後仍需使用自己的 OpenAI 帳戶／API 權限。",
        "agent_install.note.claude": "安裝後仍需使用自己的 Anthropic 登入／額度。",
        "agent_install.note.kimi": "首次啟動另需 Git for Windows，並使用自己的 Moonshot 登入／API。",
        "agent_install.note.grok": "目前只提供官方指南；ACP 實測仍需你自己的 xAI 登入／額度。",
        "agent_install.note.acpx": "社群 MIT 互通層（固定 0.13.0）；用結構化 ACP 連接已安裝及已登入的 Agent，不代表任何模型供應商。",
        "feedback.prompt": "一句話描述問題",
        "feedback.contact": "回覆電郵（可選）",
        "feedback.attach": "+ 附加畫面／診斷檔",
        "feedback.clear": "清除",
        "feedback.include_key": "附加完整 API Key／Token（只在本機以支援公鑰加密）",
        "feedback.privacy": "普通診斷遮蔽秘密但保留解析結構；完整 Key 不寫入報告、日誌或遙測。",
        "feedback.recipient": "收件者",
        "feedback.destination": "目的地",
        "feedback.key_fingerprint": "公鑰 SHA-256",
        "feedback.privacy_url": "隱私政策",
        "feedback.send": ">> 私密送出",
        "feedback.status.initial": "描述問題後即可送出；診斷不依賴任何 Agent 或 Provider。",
        "feedback.attachment.none": "未附加檔案",
        "feedback.encrypt_error": "完整 Key 加密設定不可用：{error}",
        "feedback.encrypt_unavailable": "此發行包尚未綁定可用的支援公鑰／加密元件。",
        "feedback.recipient_ready": "加密收件者：{recipient} // KEY SHA-256 {sha}",
        "feedback.file_dialog_title": "選擇最多 5 個畫面或診斷檔",
        "feedback.file_dialog_safe": "安全附件",
        "feedback.file_dialog_all": "所有檔案",
        "feedback.describe_required": "請先用一句話描述問題。",
        "feedback.key_required": "已選擇附加完整 Key，請先貼上內容。",
        "feedback.sending": "送出中...",
        "feedback.packaging": "正在本機建立私密案件包；不經過 Agent 或 Provider。",
        "feedback.local_bundle_suffix": "；本機包：{path}",
        "feedback.send_failed": "送出未完成：{error}{suffix}",
        "feedback.received_notified": "已由 HTTPS 私密收件，並確認郵件通知已送出",
        "feedback.received_notify_failed": "已由 HTTPS 私密收件；郵件通知失敗，案件仍安全保存在收件端",
        "feedback.received_notify_unknown": "已由 HTTPS 私密收件；收件端未提供郵件通知確認",
        "feedback.received_summary": "{status} // 案件 {case_id} // SHA {sha}",
        "feedback.email_opened": "已建立案件 {case_id}；郵件已開啟，請附上：{path}",
        "feedback.saved_local": "未設定私有收件端；已安全保存案件 {case_id}：{path}",
        "connection.status.initial": "秘密只進 Windows Credential Manager；MCP 只記錄 SHA-256。",
        "ccswitch.status.initial": "使用 CC Switch 官方 CLI；不讀取其資料庫或匯出憑證。",
        "connect.heading": "安全接入 // 秘密平面與協作平面分離",
        "connect.privacy": "API Key 與完整私人網址不進 MCP、SQLite、訊息、審計、收據、CLI 參數、深層連結或 Git。\n此頁只把已遮蔽的中繼資料與 SHA-256 寫入 PeerBridge。",
        "connect.native_heading": " 01  自備 Provider / Relay ",
        "connect.save_discover": ">> 儲存並查模型",
        "connect.discover": ">> 重新查模型",
        "connect.register_route": ">> 登記 Route",
        "connect.test_reply": ">> 實測一次回覆",
        "connect.ccswitch_heading": " 02  CC Switch 已保存 Provider ",
        "connect.ccswitch_refresh": ">> 重新讀取",
        "connect.ccswitch_models": ">> 取得模型",
        "connect.ccswitch_register": ">> 登記 Route",
        "connect.ccswitch_sync": ">> 同步此來源全部模型",
        "connect.ccswitch_switch": ">> 明確切換",
        "connect.ccswitch_open": ">> 開啟 CC Switch",
        "connect.identifier_chars": "{label} 只可包含英文字母、數字、點、底線、冒號或連字號。",
        "connect.safe_error": "本機接入失敗；詳細內容已隱藏以避免洩漏憑證。",
        "connect.route_registered_suffix": "；Route {route} 已登記",
        "connect.route_missing_suffix": "；尚未建立 Route",
        "connect.saved": "已安全接入 {connection}；找到 {count} 個模型 // {suffix}",
        "connect.discovering": "正在由 Windows Credential Manager 讀取並直接查詢 /v1/models...",
        "connect.discovery_failed": "模型探測失敗：{error}",
        "connect.discovered": "已直接從 API 取得 {count} 個模型 // registry SHA {sha}",
        "connect.model_unverified": "MODEL 不在剛才驗證的 Provider 模型清單內。",
        "connect.connection_missing": "找不到唯一、已啟用的 direct API connection；請先儲存並查模型。",
        "connect.route_failed": "Route 未建立：{error}",
        "connect.route_registered": "Route {route} 已登記；model={model} // SHA {sha}",
        "ccswitch.cli_missing": "找不到 CC Switch 官方 CLI。",
        "ccswitch.reading": "正在透過官方 CLI 讀取 {app} Provider（不匯出憑證）...",
        "ccswitch.read": "已讀取 {count} 個 Provider；完整網址與 API Key 未離開 CC Switch。",
        "ccswitch.choose": "請先重新讀取並選擇 CC Switch Provider。",
        "ccswitch.fetching": "正在由 CC Switch 使用其已保存憑證取得模型列表...",
        "ccswitch.fetched": "已取得 {count} 個模型；模型名稱是 Route 中繼資料，不是推理強度。",
        "ccswitch.registering": "正在經 MCP 登記 CC Switch 已遮蔽 connection 與 Route...",
        "ccswitch.syncing": "正在取得並登記此來源的全部模型；不會切換 Provider...",
        "ccswitch.no_models": "此 Provider 沒有回傳可登記模型。",
        "ccswitch.synced": "已登記 {count} 個模型 Route；CC Switch 來源沒有被切換。",
        "ccswitch.registered": "Route {route} 已登記；未自動切換 CC Switch。",
        "ccswitch.switch_title": "明確切換 CC Switch",
        "ccswitch.switch_body": "確定把 {app} 切換至「{provider}」？\nPeerBridge 不會讀取或複製其 API Key。",
        "ccswitch.switched": "已明確切換 {app} 至 {provider}。",
        "ccswitch.app_missing": "找不到 CC Switch 桌面程式。",
        "discussion.limit_integer": "AUTO // LIMIT 必須是整數",
        "status.failed": "失敗：{error}",
        "room.lobby_exists": "Lobby 已存在，請使用其他 ROOM ID。",
        "room.name_length": "ROOM NAME 必須為 1 到 200 字元。",
        "room.name_sensitive": "ROOM NAME 看似包含秘密，已拒絕寫入。",
        "announcement.network": "連接 HTTPS 公告服務（會傳送介面語言及公告游標；網絡服務可見 IP 位址）",
        "announcement.network_off": "公告網絡連線已關閉；已保存公告仍可閱讀。",
        "announcement.popup": "收到新公告時彈出通知",
        "announcement.sync": "立即同步",
        "announcement.disabled": "公告服務尚未設定；可在此頁查看已保存公告。",
        "announcement.checking": "正在背景同步公告…",
        "announcement.none": "目前沒有新公告。",
        "announcement.updated": "已同步 {count} 則新公告。",
        "announcement.error": "公告同步失敗：{error}",
        "announcement.severity": "級別",
        "announcement.title": "標題",
        "announcement.published": "發布時間",
        "announcement.popup_title": "PeerBridge 新公告",
        "announcement.open": "開啟公告欄",
        "tutorial.title": "PeerBridge 快速開始",
        "tutorial.next": "下一步",
        "tutorial.back": "上一步",
        "tutorial.done": "完成",
        "tutorial.skip": "略過",
        "tutorial.step1.title": "1 / 4  建立 Agent 接入",
        "tutorial.step1.body": "到「06 接入」新增官方、轉接或本機 Provider。官方與轉接密鑰只放入本機秘密儲存區；本機 Provider 只接受 loopback endpoint 且不需要 API key。",
        "tutorial.step2.title": "2 / 4  將 Agent 加入房間",
        "tutorial.step2.body": "在左側 Global Agent Library 選取 Agent，再拖進房間或用加入按鈕。每個房間席位可獨立選 Provider、模型與思考強度。",
        "tutorial.step3.title": "3 / 4  選擇協作方式",
        "tutorial.step3.body": "Off 只記錄；Once 平行喚醒房內 Agent 一輪；Discussion 在回合、訊息與停滯上限內討論，避免無限回覆。",
        "tutorial.step4.title": "4 / 4  查看證據與回饋",
        "tutorial.step4.body": "工作、互評、變更與審計頁保留協作痕跡。遇到問題可用「08 意見回饋」一次送出診斷；完整 Key 只會在明確勾選後本機加密。",
        "updates.checking": "正在只讀檢查 GitHub Release…",
        "updates.current": "目前已是最新版 v{version}",
        "updates.available": "有新 Alpha v{version}；不會自動下載或安裝。",
        "updates.error": "更新檢查失敗：{error}",
    },
    "zh-Hans": {
        "nav.chat": "01  对话",
        "nav.work": "02  工作板",
        "nav.review": "03  互评",
        "nav.change": "04  变更",
        "nav.audit": "05  审计",
        "nav.connect": "06  接入",
        "nav.memory": "07  记忆",
        "nav.feedback": "08  意见反馈",
        "nav.usage": "09  使用量",
        "nav.announcement": "10  公告",
        "sidebar.agent_library": "全局智能体库 // 智能体 != 模型",
        "sidebar.version": "只读查看＋MCP 发送 // v{version}",
        "sidebar.library_none": "全局智能体库 // 未选择",
        "sidebar.library_selected": "全局智能体库 // {agent}",
        "sidebar.library_empty": "全局智能体库为空",
        "sidebar.online": "在线",
        "sidebar.rooms": "房间",
        "sidebar.messages": "消息",
        "sidebar.memory": "记忆",
        "sidebar.dispatch": "派送",
        "sidebar.open_calls": "待处理调用",
        "sidebar.active": "进行中",
        "sidebar.audit": "审计",
        "sidebar.sync": "同步",
        "sidebar.dispatch_running": "执行",
        "sidebar.dispatch_retry": "重试",
        "sidebar.dispatch_failed": "失败",
        "sidebar.dispatch_completed": "完成",
        "sidebar.database_error": "数据库错误",
        "page.chat": "对话",
        "page.work": "工作板",
        "page.review": "互评",
        "page.change": "变更",
        "page.audit": "审计",
        "page.connect": "安全接入",
        "page.memory": "共享记忆",
        "page.feedback": "意见反馈",
        "page.usage": "Token 使用量",
        "page.announcement": "公告",
        "usage.total_tokens": "累计 Token",
        "usage.input_tokens": "输入 Token",
        "usage.output_tokens": "输出 Token",
        "usage.coverage": "Token 覆盖",
        "usage.dispatches": "完成／失败",
        "usage.daily": "近 30 日 Token",
        "usage.platforms": "按供应商拆分",
        "usage.today": "今日 Token",
        "usage.models": "模型使用量",
        "usage.provider": "供应商",
        "usage.model": "模型",
        "usage.agent": "智能体",
        "usage.calls": "调用",
        "usage.reported": "已回报",
        "usage.input": "输入",
        "usage.output": "输出",
        "usage.cached_input": "缓存输入",
        "usage.reasoning": "推理",
        "usage.total": "合计",
        "usage.calls_no_tokens": "调用次数（未提供 Token）",
        "usage.provider_reported_tokens": "供应商回报 Token",
        "usage.unavailable": "未提供",
        "usage.partial": "部分回报",
        "usage.derived_total": "输入加输出推算合计",
        "usage.no_data": "尚无供应商回报的 Token 数据",
        "usage.note": "只显示供应商真实回报的 Token；未提供的执行不会按字数估算。",
        "toolbar.search": "搜索",
        "toolbar.pause": "|| 暂停",
        "toolbar.refresh": ">> 刷新",
        "toolbar.refreshing": "正在刷新...",
        "toolbar.refreshed": "已刷新 {time}",
        "toolbar.refresh_failed": "刷新失败",
        "toolbar.help": "? 教程",
        "toolbar.announcements": "公告",
        "toolbar.announcements_unread": "公告 ({count})",
        "toolbar.updates": "检查更新",
        "toolbar.language": "语言",
        "chat.attach": "+ 附件",
        "chat.clear_attachments": "清除附件",
        "chat.no_attachments": "未附加文件",
        "chat.attachments_selected": "已选择 {count} 个附件；发送后以内容 SHA 安全命名。",
        "chat.attachment_note": "附件以哈希副本保存；模型能否直接理解图片取决于供应商。",
        "chat.to": "收件人",
        "chat.priority": "优先级",
        "chat.priority.low": "低",
        "chat.priority.normal": "一般",
        "chat.priority.high": "高",
        "chat.priority.critical": "紧急",
        "chat.task": "任务",
        "chat.provider": "供应商",
        "chat.model": "模型",
        "chat.reasoning": "推理强度",
        "chat.subject": "主题",
        "chat.new_room": "+ 新房间",
        "chat.join_control": "+ 加入控制",
        "chat.older": "< 较早",
        "chat.latest": "最新 >",
        "chat.focus": "⛶ 全屏对话",
        "chat.exit_focus": "退出全屏",
        "chat.auto": "自动",
        "chat.mode.off": "关闭自动回复",
        "chat.mode.once": "每个 Agent 回复一轮",
        "chat.mode.discussion": "有限持续讨论",
        "chat.rounds": "回合",
        "chat.messages": "消息",
        "chat.stagnation": "停滞",
        "chat.apply": "应用",
        "chat.pause": "暂停",
        "chat.resume": "恢复",
        "chat.continue": "继续",
        "chat.stop": "停止",
        "chat.room_seats": "房间席位",
        "chat.apply_seat": "+ 应用席位",
        "chat.remove_seat": "- 移除",
        "chat.manage_providers": "06 接入",
        "chat.send": ">> MCP 发送",
        "chat.message_hint": "Enter 发送 / Shift+Enter 换行",
        "chat.join_to_send": "你尚未加入此房间。请按“+ 加入控制”加入 human-operator 席位后再发送。",
        "chat.seat_hint": "选择 Global Agent，再加入当前房间。",
        "chat.recipient.all": "全体 Agent (*)",
        "chat.route.direct": "Agent 默认 Route",
        "chat.route.broadcast": "房间席位已指定的模型",
        "chat.route.unregistered": "未登记来源（到 06 接入）",
        "chat.route_unique_required": "找不到唯一 Route；请重新选择 Provider、模型与思考强度。",
        "chat.required_fields": "需要任务、主题和消息内容。",
        "chat.broadcast_missing_routes": "全体发送已停止：请先用 Agent 方格右侧 ▼ 设置模型：{agents}",
        "chat.routed_broadcast_forbidden": "指定模型路由时必须选择一个 Agent，不能广播。",
        "chat.sending": "正在通过 MCP stdio 写入 {room} 的 SHA 绑定消息...",
        "chat.send_failed": "发送失败：{error}",
        "chat.sent": "{fanout}已发送至 {room} // SHA {sha} // {created}",
        "chat.fanout": "分派至 {count} 个 Agent // ",
        "chat.secret_rejected": "消息似乎包含 API Key 或 Token；为避免写入审计库，已拒绝发送。",
        "chat.body_too_long": "消息超过 20,000 个字符上限。",
        "chat.model.default": "供应商默认模型",
        "chat.reasoning.default": "供应商默认推理",
        "chat.lobby_hint": "Lobby 默认包含 Global Library Agent；拖出会建立可审计的接收停用记录。",
        "seat.no_connections": "{agent} 没有可安全查询的 Provider connection。",
        "seat.refreshing": "正在安全重新查询 {agent} 的 Provider 模型列表...",
        "seat.selected": "{agent} 已选择；可修改 Provider、模型和推理强度后应用。",
        "seat.no_route": "{agent} 尚未登记可执行模型 Route。",
        "seat.multiple_providers": "{agent} 有多个 Provider；请先选择。",
        "seat.select_model": "请选择此 Agent 要使用的模型。",
        "seat.select_reasoning": "请选择此模型的推理强度。",
        "seat.advertised": "API 已列出 {model}；按“应用席位”会再次验证并建立 Route。",
        "seat.configured": "设置完成：{agent} → {model} / {reasoning}；按“应用席位”。",
        "seat.route_unique": "找不到唯一 Route；请重新选择 Provider、模型和推理强度。",
        "seat.drop_agent_cancelled": "拖放已取消 // Agent 仍留在全局智能体库，未建立房间席位。",
        "seat.drop_seat_cancelled": "拖放已取消 // 席位仍在房间；拖到左侧全局智能体库才会移除。",
        "seat.menu_current": "当前：{route}",
        "seat.menu_options": "可选 {models} 个模型 / {providers} 个 Provider",
        "seat.menu_advertised": " · API 已列出，点击后验证",
        "seat.menu_no_route": "没有可用 Route，请先到 06 接入",
        "seat.menu_refresh": "重新同步 Provider 模型列表",
        "seat.menu_remove": "移除此房间席位（保留历史）",
        "seat.select_agent": "请先从全局智能体库选择 Agent。",
        "seat.incomplete": "尚未完成模型设置：请选择 Provider、模型和推理强度。",
        "seat.missing_provider_identity": "未登记模型缺少 Provider identity；已停止应用。",
        "seat.no_revalidatable_connection": "找不到唯一、可安全重新验证的 Provider connection。",
        "seat.provider_model_removed": "Provider 已不再列出所选模型；没有建立 Route。",
        "seat.codex_identity_incomplete": "官方 Codex 模型 identity 不完整；已停止应用。",
        "seat.codex_model_removed": "Codex 已不再列出所选模型；没有建立 Route。",
        "seat.codex_reasoning_removed": "所选推理强度不再受这个 Codex 模型支持。",
        "seat.select_remove": "请先选择要移除的房间席位。",
        "seat.keep_control": "控制者席位必须保留，以维持房间操作权。",
        "seat.confirm_remove": "停止 {agent} 接收 {room} 的新消息？\n现有消息与历史不会删除。",
        "seat.lobby_bound_only": "Lobby 只唤醒已绑定 Route 的席位；在 Agent 方格 ▼ 选择模型。",
        "provider.display_name_required": "DISPLAY NAME 不可留空。",
        "provider.class_invalid": "CLASS 必须是 official、relay 或 local。",
        "provider.endpoint_required": "ENDPOINT 不可留空。",
        "provider.local_loopback_only": "LOCAL Provider 仅允许 loopback endpoint。",
        "provider.api_key_required": "OFFICIAL 与 RELAY Provider 必须提供 API KEY。",
        "provider.show_api_key": "显示",
        "provider.hide_api_key": "隐藏",
        "provider.saving": "正在安全保存 Provider descriptor，然后经 MCP 登记 SHA 绑定 metadata...",
        "provider.save_failed": "Provider 验证或 MCP 登记未完成；输入已清空；credential descriptor 可能已保存。{error}",
        "provider.test_route_missing": "找不到唯一、已启用的 Route；请先完成登记。",
        "provider.test_confirm_title": "确认一次真实 Provider 测试",
        "provider.test_confirm_body": "将向 {agent} / {model} 发送一次最小推理请求。这可能消耗额度；只有真实回复才能验证登录、权限和余额。继续？",
        "provider.test_queue_failed": "Provider 实测未能进入队列：{error}",
        "provider.test_queued": "实测已排入 Lobby：{task} // SHA {sha}。聊天记录会显示回复或明确终止原因。",
        "agent_install.heading": " 00  Agent 终端与 ACP 互通层 // 安装与更新 ",
        "agent_install.intro": "官方 Agent 与社区互通层会分别标示；仅执行固定、经审核的软件包，不接受聊天室、Provider 或用户提供的安装网址／命令。安装不包含登录、订阅或模型额度。",
        "agent_install.detect_all": ">> 重新检测全部终端",
        "agent_install.install": "安装",
        "agent_install.update": "更新",
        "agent_install.open_guide": "官方指南",
        "agent_install.docs": "说明",
        "agent_install.detecting": "正在检测…",
        "agent_install.detect_failed": "终端检测失败；未执行任何安装。",
        "agent_install.installed": "已安装 // {version}",
        "agent_install.not_installed": "未安装。",
        "agent_install.version_unknown": "版本未报告",
        "agent_install.manual_only": "已打开官方指南；Windows 自动安装来源尚未通过供应商验证。",
        "agent_install.confirm_title": "确认官方终端安装",
        "agent_install.confirm_body": "即将在可见终端用官方软件包管理器安装／更新 {name}：\n\n{package}\n\nPeerBridge 不会替你登录，也不能提供订阅或模型额度。继续？",
        "agent_install.launch_failed": "无法启动官方软件包管理器：{error}",
        "agent_install.running": "安装／更新正在独立终端执行；完成前请勿关闭该终端。",
        "agent_install.completed": "软件包管理器已完成；正在重新检测。",
        "agent_install.failed": "软件包管理器以代码 {code} 结束；请查看可见终端的原始错误。",
        "agent_install.note.codex": "安装后仍需使用自己的 OpenAI 账户／API 权限。",
        "agent_install.note.claude": "安装后仍需使用自己的 Anthropic 登录／额度。",
        "agent_install.note.kimi": "首次启动另需 Git for Windows，并使用自己的 Moonshot 登录／API。",
        "agent_install.note.grok": "当前只提供官方指南；ACP 实测仍需你自己的 xAI 登录／额度。",
        "agent_install.note.acpx": "社区 MIT 互通层（固定 0.13.0）；用结构化 ACP 连接已安装及已登录的 Agent，不代表任何模型供应商。",
        "feedback.prompt": "一句话描述问题",
        "feedback.contact": "回复邮箱（可选）",
        "feedback.attach": "+ 附加画面／诊断文件",
        "feedback.clear": "清除",
        "feedback.include_key": "附加完整 API Key／Token（仅在本机用支持公钥加密）",
        "feedback.privacy": "普通诊断会遮蔽秘密但保留解析结构；完整 Key 不写入报告、日志或遥测。",
        "feedback.recipient": "收件人",
        "feedback.destination": "目的地",
        "feedback.key_fingerprint": "公钥 SHA-256",
        "feedback.privacy_url": "隐私政策",
        "feedback.send": ">> 私密发送",
        "feedback.status.initial": "描述问题后即可发送；诊断不依赖任何 Agent 或 Provider。",
        "feedback.attachment.none": "未附加文件",
        "feedback.encrypt_error": "完整 Key 加密设置不可用：{error}",
        "feedback.encrypt_unavailable": "此发行包尚未绑定可用的支持公钥／加密组件。",
        "feedback.recipient_ready": "加密收件人：{recipient} // KEY SHA-256 {sha}",
        "feedback.file_dialog_title": "选择最多 5 个画面或诊断文件",
        "feedback.file_dialog_safe": "安全附件",
        "feedback.file_dialog_all": "所有文件",
        "feedback.describe_required": "请先用一句话描述问题。",
        "feedback.key_required": "已选择附加完整 Key，请先粘贴内容。",
        "feedback.sending": "发送中...",
        "feedback.packaging": "正在本机建立私密案件包；不经过 Agent 或 Provider。",
        "feedback.local_bundle_suffix": "；本机包：{path}",
        "feedback.send_failed": "发送未完成：{error}{suffix}",
        "feedback.received_notified": "已由 HTTPS 私密收件，并确认邮件通知已发送",
        "feedback.received_notify_failed": "已由 HTTPS 私密收件；邮件通知失败，案件仍安全保存在收件端",
        "feedback.received_notify_unknown": "已由 HTTPS 私密收件；收件端未提供邮件通知确认",
        "feedback.received_summary": "{status} // 案件 {case_id} // SHA {sha}",
        "feedback.email_opened": "已建立案件 {case_id}；邮件已打开，请附上：{path}",
        "feedback.saved_local": "未设置私有收件端；已安全保存案件 {case_id}：{path}",
        "connection.status.initial": "秘密只进入 Windows Credential Manager；MCP 只记录 SHA-256。",
        "ccswitch.status.initial": "使用 CC Switch 官方 CLI；不读取其数据库或导出凭据。",
        "connect.heading": "安全接入 // 秘密平面与协作平面分离",
        "connect.privacy": "API Key 和完整私人网址不进入 MCP、SQLite、消息、审计、收据、CLI 参数、深层链接或 Git。\n此页只把已遮蔽的元数据和 SHA-256 写入 PeerBridge。",
        "connect.native_heading": " 01  自备 Provider / Relay ",
        "connect.save_discover": ">> 保存并查询模型",
        "connect.discover": ">> 重新查询模型",
        "connect.register_route": ">> 登记 Route",
        "connect.test_reply": ">> 实测一次回复",
        "connect.ccswitch_heading": " 02  CC Switch 已保存 Provider ",
        "connect.ccswitch_refresh": ">> 重新读取",
        "connect.ccswitch_models": ">> 获取模型",
        "connect.ccswitch_register": ">> 登记 Route",
        "connect.ccswitch_sync": ">> 同步此来源全部模型",
        "connect.ccswitch_switch": ">> 明确切换",
        "connect.ccswitch_open": ">> 打开 CC Switch",
        "connect.identifier_chars": "{label} 只可包含英文字母、数字、点、下划线、冒号或连字符。",
        "connect.safe_error": "本机接入失败；详细内容已隐藏以避免泄漏凭据。",
        "connect.route_registered_suffix": "；Route {route} 已登记",
        "connect.route_missing_suffix": "；尚未建立 Route",
        "connect.saved": "已安全接入 {connection}；找到 {count} 个模型 // {suffix}",
        "connect.discovering": "正在从 Windows Credential Manager 读取并直接查询 /v1/models...",
        "connect.discovery_failed": "模型探测失败：{error}",
        "connect.discovered": "已直接从 API 获取 {count} 个模型 // registry SHA {sha}",
        "connect.model_unverified": "MODEL 不在刚才验证的 Provider 模型列表内。",
        "connect.connection_missing": "找不到唯一、已启用的 direct API connection；请先保存并查询模型。",
        "connect.route_failed": "Route 未建立：{error}",
        "connect.route_registered": "Route {route} 已登记；model={model} // SHA {sha}",
        "ccswitch.cli_missing": "找不到 CC Switch 官方 CLI。",
        "ccswitch.reading": "正在通过官方 CLI 读取 {app} Provider（不导出凭据）...",
        "ccswitch.read": "已读取 {count} 个 Provider；完整网址与 API Key 未离开 CC Switch。",
        "ccswitch.choose": "请先重新读取并选择 CC Switch Provider。",
        "ccswitch.fetching": "正在由 CC Switch 使用其已保存凭据获取模型列表...",
        "ccswitch.fetched": "已获取 {count} 个模型；模型名称是 Route 元数据，不是推理强度。",
        "ccswitch.registering": "正在经 MCP 登记 CC Switch 已遮蔽 connection 与 Route...",
        "ccswitch.syncing": "正在获取并登记此来源的全部模型；不会切换 Provider...",
        "ccswitch.no_models": "此 Provider 没有返回可登记模型。",
        "ccswitch.synced": "已登记 {count} 个模型 Route；CC Switch 来源没有被切换。",
        "ccswitch.registered": "Route {route} 已登记；未自动切换 CC Switch。",
        "ccswitch.switch_title": "明确切换 CC Switch",
        "ccswitch.switch_body": "确定把 {app} 切换至“{provider}”？\nPeerBridge 不会读取或复制其 API Key。",
        "ccswitch.switched": "已明确切换 {app} 至 {provider}。",
        "ccswitch.app_missing": "找不到 CC Switch 桌面程序。",
        "discussion.limit_integer": "AUTO // LIMIT 必须是整数",
        "status.failed": "失败：{error}",
        "room.lobby_exists": "Lobby 已存在，请使用其他 ROOM ID。",
        "room.name_length": "ROOM NAME 必须为 1 到 200 个字符。",
        "room.name_sensitive": "ROOM NAME 似乎包含秘密，已拒绝写入。",
        "announcement.network": "连接 HTTPS 公告服务（会发送界面语言及公告游标；网络服务可见 IP 地址）",
        "announcement.network_off": "公告网络连接已关闭；已保存公告仍可阅读。",
        "announcement.popup": "收到新公告时弹出通知",
        "announcement.sync": "立即同步",
        "announcement.disabled": "公告服务尚未设置；可在此页查看已保存公告。",
        "announcement.checking": "正在后台同步公告…",
        "announcement.none": "当前没有新公告。",
        "announcement.updated": "已同步 {count} 条新公告。",
        "announcement.error": "公告同步失败：{error}",
        "announcement.severity": "级别",
        "announcement.title": "标题",
        "announcement.published": "发布时间",
        "announcement.popup_title": "PeerBridge 新公告",
        "announcement.open": "打开公告栏",
        "tutorial.title": "PeerBridge 快速开始",
        "tutorial.next": "下一步",
        "tutorial.back": "上一步",
        "tutorial.done": "完成",
        "tutorial.skip": "跳过",
        "tutorial.step1.title": "1 / 4  建立 Agent 接入",
        "tutorial.step1.body": "到“06 接入”新增官方、中转或本机 Provider。官方与中转密钥只进入本机秘密存储；本机 Provider 仅接受 loopback endpoint 且不需要 API key。",
        "tutorial.step2.title": "2 / 4  将 Agent 加入房间",
        "tutorial.step2.body": "在左侧 Global Agent Library 选择 Agent，再拖入房间或使用加入按钮。每个房间席位可独立选择 Provider、模型和思考强度。",
        "tutorial.step3.title": "3 / 4  选择协作方式",
        "tutorial.step3.body": "Off 只记录；Once 并行唤醒房内 Agent 一轮；Discussion 在回合、消息和停滞上限内讨论，避免无限回复。",
        "tutorial.step4.title": "4 / 4  查看证据与反馈",
        "tutorial.step4.body": "工作、互评、变更和审计页保留协作痕迹。遇到问题可用“08 意见反馈”一次提交诊断；完整 Key 仅在明确勾选后本机加密。",
        "updates.checking": "正在只读检查 GitHub Release…",
        "updates.current": "当前已是最新版 v{version}",
        "updates.available": "有新 Alpha v{version}；不会自动下载或安装。",
        "updates.error": "更新检查失败：{error}",
    },
    "en": {
        "nav.chat": "01  Chat",
        "nav.work": "02  Work",
        "nav.review": "03  Reviews",
        "nav.change": "04  Changes",
        "nav.audit": "05  Audit",
        "nav.connect": "06  Providers",
        "nav.memory": "07  Memory",
        "nav.feedback": "08  Feedback",
        "nav.usage": "09  Usage",
        "nav.announcement": "10  Announcements",
        "sidebar.agent_library": "GLOBAL AGENT LIBRARY // AGENT != MODEL",
        "sidebar.version": "READ ONLY + MCP SEND // v{version}",
        "sidebar.library_none": "GLOBAL AGENT LIBRARY // NONE SELECTED",
        "sidebar.library_selected": "GLOBAL AGENT LIBRARY // {agent}",
        "sidebar.library_empty": "GLOBAL AGENT LIBRARY EMPTY",
        "sidebar.online": "ONLINE",
        "sidebar.rooms": "ROOMS",
        "sidebar.messages": "MESSAGES",
        "sidebar.memory": "MEMORY",
        "sidebar.dispatch": "DISPATCH",
        "sidebar.open_calls": "OPEN CALL",
        "sidebar.active": "ACTIVE",
        "sidebar.audit": "AUDIT",
        "sidebar.sync": "SYNC",
        "sidebar.dispatch_running": "RUN",
        "sidebar.dispatch_retry": "RETRY",
        "sidebar.dispatch_failed": "FAIL",
        "sidebar.dispatch_completed": "DONE",
        "sidebar.database_error": "DATABASE ERROR",
        "page.chat": "Chat",
        "page.work": "Workboard",
        "page.review": "Peer reviews",
        "page.change": "Changes",
        "page.audit": "Audit",
        "page.connect": "Secure providers",
        "page.memory": "Shared memory",
        "page.feedback": "Feedback",
        "page.usage": "Token / usage",
        "page.announcement": "Announcements",
        "usage.total_tokens": "Reported tokens",
        "usage.input_tokens": "Input tokens",
        "usage.output_tokens": "Output tokens",
        "usage.coverage": "Token coverage",
        "usage.dispatches": "Complete / failed",
        "usage.daily": "30-day token usage",
        "usage.platforms": "Usage by provider",
        "usage.today": "Tokens today",
        "usage.models": "Usage by model",
        "usage.provider": "Provider",
        "usage.model": "Model",
        "usage.agent": "Agent",
        "usage.calls": "Calls",
        "usage.reported": "Reported",
        "usage.input": "Input",
        "usage.output": "Output",
        "usage.cached_input": "Cached input",
        "usage.reasoning": "Reasoning",
        "usage.total": "Total",
        "usage.calls_no_tokens": "Calls (tokens unavailable)",
        "usage.provider_reported_tokens": "Provider-reported tokens",
        "usage.unavailable": "Unavailable",
        "usage.partial": "Partial",
        "usage.derived_total": "Input plus output derived total",
        "usage.no_data": "No provider-reported token data yet",
        "usage.note": "Only provider-reported tokens are shown; missing usage is never estimated from text length.",
        "toolbar.search": "Search",
        "toolbar.pause": "|| Pause",
        "toolbar.refresh": ">> Refresh",
        "toolbar.refreshing": "Refreshing...",
        "toolbar.refreshed": "Refreshed {time}",
        "toolbar.refresh_failed": "Refresh failed",
        "toolbar.help": "? Tutorial",
        "toolbar.announcements": "Announcements",
        "toolbar.announcements_unread": "Announcements ({count})",
        "toolbar.updates": "Check updates",
        "toolbar.language": "Language",
        "chat.attach": "+ Attach",
        "chat.clear_attachments": "Clear attachments",
        "chat.no_attachments": "No attachments",
        "chat.attachments_selected": "{count} attachment(s) selected; content SHA names are used after sending.",
        "chat.attachment_note": "Attachments use hashed copies; direct image understanding depends on the provider.",
        "chat.to": "To",
        "chat.priority": "Priority",
        "chat.priority.low": "Low",
        "chat.priority.normal": "Normal",
        "chat.priority.high": "High",
        "chat.priority.critical": "Critical",
        "chat.task": "Task",
        "chat.provider": "Provider",
        "chat.model": "Model",
        "chat.reasoning": "Reasoning",
        "chat.subject": "Subject",
        "chat.new_room": "+ New room",
        "chat.join_control": "+ Join control",
        "chat.older": "< Older",
        "chat.latest": "Latest >",
        "chat.focus": "⛶ Focus chat",
        "chat.exit_focus": "Exit focus",
        "chat.auto": "Auto",
        "chat.mode.off": "Automation off",
        "chat.mode.once": "One reply per agent",
        "chat.mode.discussion": "Bounded discussion",
        "chat.rounds": "Rounds",
        "chat.messages": "Messages",
        "chat.stagnation": "Stall",
        "chat.apply": "Apply",
        "chat.pause": "Pause",
        "chat.resume": "Resume",
        "chat.continue": "Continue",
        "chat.stop": "Stop",
        "chat.room_seats": "Room seats",
        "chat.apply_seat": "+ Apply seat",
        "chat.remove_seat": "- Remove",
        "chat.manage_providers": "06 Providers",
        "chat.send": ">> Send via MCP",
        "chat.message_hint": "Enter to send / Shift+Enter for newline",
        "chat.join_to_send": "You are not seated in this room. Click '+ Join control' to add the human-operator seat before sending.",
        "chat.seat_hint": "Select a Global Agent, then add it to this room.",
        "chat.recipient.all": "All Agents (*)",
        "chat.route.direct": "Agent default route",
        "chat.route.broadcast": "Models assigned to room seats",
        "chat.route.unregistered": "No registered source (open 06 Providers)",
        "chat.route_unique_required": "No unique route matches this selection. Reselect the provider, model, and reasoning effort.",
        "chat.required_fields": "Task, subject, and message body are required.",
        "chat.broadcast_missing_routes": "Broadcast stopped. Assign a model from each Agent card's ▼ menu first: {agents}",
        "chat.routed_broadcast_forbidden": "A model-specific route requires one Agent recipient and cannot be broadcast.",
        "chat.sending": "Writing a SHA-bound message to {room} through MCP stdio...",
        "chat.send_failed": "Send failed: {error}",
        "chat.sent": "{fanout}Sent to {room} // SHA {sha} // {created}",
        "chat.fanout": "FANOUT {count} AGENTS // ",
        "chat.secret_rejected": "The message appears to contain an API key or token and was rejected before entering the audit database.",
        "chat.body_too_long": "The message exceeds the 20,000-character limit.",
        "chat.model.default": "Provider default model",
        "chat.reasoning.default": "Provider default reasoning",
        "chat.lobby_hint": "Lobby includes Global Library Agents by default; dragging one out creates an auditable receive opt-out.",
        "seat.no_connections": "{agent} has no provider connection that can be queried safely.",
        "seat.refreshing": "Safely refreshing the provider model catalog for {agent}...",
        "seat.selected": "Selected {agent}. Choose a provider, model, and reasoning level, then apply.",
        "seat.no_route": "{agent} has no registered executable model route.",
        "seat.multiple_providers": "{agent} has multiple providers. Select one first.",
        "seat.select_model": "Select the model this Agent should use.",
        "seat.select_reasoning": "Select a reasoning level for this model.",
        "seat.advertised": "The API advertises {model}. Apply the seat to verify it again and create the route.",
        "seat.configured": "Ready: {agent} → {model} / {reasoning}. Apply the seat.",
        "seat.route_unique": "No unique route was found. Select the provider, model, and reasoning level again.",
        "seat.drop_agent_cancelled": "DROP CANCELLED // Agent remains in the Global Agent Library; no room seat was created.",
        "seat.drop_seat_cancelled": "DROP CANCELLED // Seat remains in the room; drag it to the Global Agent Library to remove it.",
        "seat.menu_current": "Current: {route}",
        "seat.menu_options": "{models} model(s) / {providers} provider(s) available",
        "seat.menu_advertised": " · API advertised; click to verify",
        "seat.menu_no_route": "No route is available. Configure one under 06 Connect.",
        "seat.menu_refresh": "Refresh provider model catalog",
        "seat.menu_remove": "Remove this room seat (keep history)",
        "seat.select_agent": "Select an Agent from the Global Agent Library first.",
        "seat.incomplete": "Model setup is incomplete. Select a provider, model, and reasoning level.",
        "seat.missing_provider_identity": "The unregistered model lacks provider identity. Apply was stopped.",
        "seat.no_revalidatable_connection": "No unique provider connection can be revalidated safely.",
        "seat.provider_model_removed": "The provider no longer advertises the selected model. No route was created.",
        "seat.codex_identity_incomplete": "Official Codex model identity is incomplete. Apply was stopped.",
        "seat.codex_model_removed": "Codex no longer advertises the selected model. No route was created.",
        "seat.codex_reasoning_removed": "The selected reasoning level is no longer supported by this Codex model.",
        "seat.select_remove": "Select the room seat to remove first.",
        "seat.keep_control": "Keep the control-operator seat so the room remains manageable.",
        "seat.confirm_remove": "Stop {agent} from receiving new messages in {room}?\nExisting messages and history will be preserved.",
        "seat.lobby_bound_only": "Lobby wakes only seats with bound routes. Choose a model from the Agent card ▼ menu.",
        "provider.display_name_required": "DISPLAY NAME is required.",
        "provider.class_invalid": "CLASS must be official, relay, or local.",
        "provider.endpoint_required": "ENDPOINT is required.",
        "provider.local_loopback_only": "LOCAL providers accept loopback endpoints only.",
        "provider.api_key_required": "OFFICIAL and RELAY providers require an API KEY.",
        "provider.show_api_key": "Show",
        "provider.hide_api_key": "Hide",
        "provider.saving": "Saving the provider descriptor securely, then registering SHA-bound metadata through MCP...",
        "provider.save_failed": "Provider validation or MCP registration did not complete. Inputs were cleared; the credential descriptor may have been saved. {error}",
        "provider.test_route_missing": "No unique enabled route was found. Register it first.",
        "provider.test_confirm_title": "Confirm one real provider test",
        "provider.test_confirm_body": "This sends one minimal inference request to {agent} / {model}. It may consume provider credit. Only a real response can verify login, access, and balance. Continue?",
        "provider.test_queue_failed": "The provider test could not be queued: {error}",
        "provider.test_queued": "Test queued in Lobby: {task} // SHA {sha}. Chat history will show the reply or an explicit terminal reason.",
        "agent_install.heading": " 00  Agent terminals and ACP interoperability // Install and update ",
        "agent_install.intro": "Official Agents and community runtimes are labelled separately. Only fixed, reviewed packages can run; chat messages, providers, and user-supplied installer URLs or commands are never accepted. Installation does not include login, subscription, or model credit.",
        "agent_install.detect_all": ">> Detect all terminals",
        "agent_install.install": "Install",
        "agent_install.update": "Update",
        "agent_install.open_guide": "Official guide",
        "agent_install.docs": "Docs",
        "agent_install.detecting": "Detecting…",
        "agent_install.detect_failed": "Terminal detection failed; no installer was run.",
        "agent_install.installed": "Installed // {version}",
        "agent_install.not_installed": "Not installed.",
        "agent_install.version_unknown": "version not reported",
        "agent_install.manual_only": "Opened the official guide. No publisher-verified Windows auto-installer is available yet.",
        "agent_install.confirm_title": "Confirm official terminal installation",
        "agent_install.confirm_body": "A visible terminal will install or update {name} through the publisher package manager:\n\n{package}\n\nPeerBridge cannot sign you in or supply a subscription or model credit. Continue?",
        "agent_install.launch_failed": "Could not start the official package manager: {error}",
        "agent_install.running": "Install/update is running in a separate visible terminal. Keep it open until completion.",
        "agent_install.completed": "Package manager completed; detecting again.",
        "agent_install.failed": "Package manager exited with code {code}. Read the original error in its visible terminal.",
        "agent_install.note.codex": "Your own OpenAI account/API access is still required after installation.",
        "agent_install.note.claude": "Your own Anthropic login/credit is still required after installation.",
        "agent_install.note.kimi": "First launch also needs Git for Windows and your own Moonshot login/API.",
        "agent_install.note.grok": "Official guide only for now; ACP testing still needs your own xAI login/credit.",
        "agent_install.note.acpx": "Community MIT interoperability runtime (pinned to 0.13.0). It connects installed and authenticated Agents over structured ACP and represents no model provider.",
        "feedback.prompt": "Describe the problem in one message",
        "feedback.contact": "Reply email (optional)",
        "feedback.attach": "+ Attach screenshot / diagnostic",
        "feedback.clear": "Clear",
        "feedback.include_key": "Include full API key/token (encrypted locally to support key)",
        "feedback.privacy": "Normal diagnostics redact secrets but preserve parser structure. Full keys never enter reports, logs, or telemetry.",
        "feedback.recipient": "Recipient",
        "feedback.destination": "Destination",
        "feedback.key_fingerprint": "Public key SHA-256",
        "feedback.privacy_url": "Privacy policy",
        "feedback.send": ">> Send privately",
        "feedback.status.initial": "Describe the problem, then send it. Diagnostics do not depend on any Agent or provider.",
        "feedback.attachment.none": "No attachment selected",
        "feedback.encrypt_error": "Full-key encryption is unavailable: {error}",
        "feedback.encrypt_unavailable": "This build has no usable support public key or encryption component.",
        "feedback.recipient_ready": "Encrypted recipient: {recipient} // KEY SHA-256 {sha}",
        "feedback.file_dialog_title": "Choose up to 5 screenshots or diagnostic files",
        "feedback.file_dialog_safe": "Safe attachments",
        "feedback.file_dialog_all": "All files",
        "feedback.describe_required": "Describe the problem in one message first.",
        "feedback.key_required": "Full-key attachment is enabled. Paste the value first.",
        "feedback.sending": "Sending...",
        "feedback.packaging": "Building a private case bundle locally without any Agent or provider.",
        "feedback.local_bundle_suffix": "; local bundle: {path}",
        "feedback.send_failed": "Send did not complete: {error}{suffix}",
        "feedback.received_notified": "Received privately over HTTPS; email notification delivery was confirmed",
        "feedback.received_notify_failed": "Received privately over HTTPS; email notification failed, but the case remains stored safely",
        "feedback.received_notify_unknown": "Received privately over HTTPS; the endpoint did not confirm email notification delivery",
        "feedback.received_summary": "{status} // case {case_id} // SHA {sha}",
        "feedback.email_opened": "Created case {case_id}; attach this file to the opened email: {path}",
        "feedback.saved_local": "No private intake endpoint is configured. Case {case_id} was saved safely at {path}",
        "connection.status.initial": "Secrets stay in Windows Credential Manager; MCP records SHA-256 only.",
        "ccswitch.status.initial": "Uses the official CC Switch CLI without reading its database or exporting credentials.",
        "connect.heading": "Secure connections // secrets and collaboration stay separated",
        "connect.privacy": "API keys and full private URLs never enter MCP, SQLite, messages, audit, receipts, CLI arguments, deep links, or Git.\nThis page records only redacted metadata and SHA-256 in PeerBridge.",
        "connect.native_heading": " 01  Bring your own provider / relay ",
        "connect.save_discover": ">> Save and discover models",
        "connect.discover": ">> Discover again",
        "connect.register_route": ">> Register route",
        "connect.test_reply": ">> Test one real reply",
        "connect.ccswitch_heading": " 02  Providers saved in CC Switch ",
        "connect.ccswitch_refresh": ">> Reload",
        "connect.ccswitch_models": ">> Get models",
        "connect.ccswitch_register": ">> Register route",
        "connect.ccswitch_sync": ">> Sync all models from this source",
        "connect.ccswitch_switch": ">> Switch explicitly",
        "connect.ccswitch_open": ">> Open CC Switch",
        "connect.identifier_chars": "{label} may contain letters, numbers, dots, underscores, colons, or hyphens only.",
        "connect.safe_error": "Local connection failed. Details were hidden to prevent credential leakage.",
        "connect.route_registered_suffix": "; route {route} registered",
        "connect.route_missing_suffix": "; no route created",
        "connect.saved": "Connected {connection} safely; found {count} model(s) // {suffix}",
        "connect.discovering": "Reading from Windows Credential Manager and querying /v1/models directly...",
        "connect.discovery_failed": "Model discovery failed: {error}",
        "connect.discovered": "Received {count} model(s) directly from the API // registry SHA {sha}",
        "connect.model_unverified": "MODEL was not present in the provider catalog just verified.",
        "connect.connection_missing": "No unique enabled direct API connection was found. Save and discover models first.",
        "connect.route_failed": "Route was not created: {error}",
        "connect.route_registered": "Route {route} registered; model={model} // SHA {sha}",
        "ccswitch.cli_missing": "The official CC Switch CLI was not found.",
        "ccswitch.reading": "Reading {app} providers through the official CLI without exporting credentials...",
        "ccswitch.read": "Read {count} provider(s). Full URLs and API keys never left CC Switch.",
        "ccswitch.choose": "Reload and select a CC Switch provider first.",
        "ccswitch.fetching": "Using credentials saved by CC Switch to retrieve the model catalog...",
        "ccswitch.fetched": "Retrieved {count} model(s). Model names are route metadata, not reasoning levels.",
        "ccswitch.registering": "Registering a redacted CC Switch connection and route through MCP...",
        "ccswitch.syncing": "Retrieving and registering every model from this source without switching providers...",
        "ccswitch.no_models": "This provider returned no models that can be registered.",
        "ccswitch.synced": "Registered {count} model route(s). The CC Switch source was not switched.",
        "ccswitch.registered": "Route {route} registered. CC Switch was not switched automatically.",
        "ccswitch.switch_title": "Switch CC Switch explicitly",
        "ccswitch.switch_body": "Switch {app} to “{provider}”?\nPeerBridge will not read or copy its API key.",
        "ccswitch.switched": "Explicitly switched {app} to {provider}.",
        "ccswitch.app_missing": "The CC Switch desktop application was not found.",
        "discussion.limit_integer": "AUTO // LIMIT must be an integer",
        "status.failed": "Failed: {error}",
        "room.lobby_exists": "Lobby already exists. Use another ROOM ID.",
        "room.name_length": "ROOM NAME must contain 1 to 200 characters.",
        "room.name_sensitive": "ROOM NAME appears to contain a secret and was rejected.",
        "announcement.network": "Connect to the HTTPS announcement service (sends UI locale and announcement cursor; network services can see your IP address)",
        "announcement.network_off": "Announcement network access is off. Saved notices remain available.",
        "announcement.popup": "Pop up when a new announcement arrives",
        "announcement.sync": "Sync now",
        "announcement.disabled": "Announcement service is not configured. Saved notices remain available here.",
        "announcement.checking": "Syncing announcements in the background...",
        "announcement.none": "There are no new announcements.",
        "announcement.updated": "Synced {count} new announcement(s).",
        "announcement.error": "Announcement sync failed: {error}",
        "announcement.severity": "Severity",
        "announcement.title": "Title",
        "announcement.published": "Published",
        "announcement.popup_title": "New PeerBridge announcement",
        "announcement.open": "Open announcements",
        "tutorial.title": "PeerBridge quick start",
        "tutorial.next": "Next",
        "tutorial.back": "Back",
        "tutorial.done": "Done",
        "tutorial.skip": "Skip",
        "tutorial.step1.title": "1 / 4  Connect agents",
        "tutorial.step1.body": "Use Secure providers to add an official, relay, or local route. Official and relay keys stay in local secret storage; local providers accept loopback endpoints only and need no API key.",
        "tutorial.step2.title": "2 / 4  Add agents to a room",
        "tutorial.step2.body": "Select an agent in the Global Agent Library, then drag it into a room or use Add. Each room seat can choose its own provider, model, and reasoning effort.",
        "tutorial.step3.title": "3 / 4  Choose collaboration mode",
        "tutorial.step3.body": "Off records only; Once wakes room agents for one parallel round; Discussion runs within round, message, and stagnation limits to prevent reply loops.",
        "tutorial.step4.title": "4 / 4  Inspect evidence and send feedback",
        "tutorial.step4.body": "Work, reviews, changes, and audit preserve collaboration evidence. Feedback sends diagnostics once; a full key is encrypted locally only after explicit opt-in.",
        "updates.checking": "Checking GitHub Release metadata (read only)…",
        "updates.current": "This is the latest release, v{version}",
        "updates.available": "New Alpha v{version} is available; nothing will be downloaded or installed automatically.",
        "updates.error": "Update check failed: {error}",
    },
}


def _preferences_path(project_root: Path) -> Path:
    return project_root.resolve() / ".peerbridge" / "ui-preferences.json"


def _atomic_write(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{secrets.token_hex(8)}.tmp")
    temporary.write_text(
        json.dumps(dict(payload), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def default_preferences() -> dict[str, Any]:
    return {
        "schema": UI_PREFERENCES_SCHEMA,
        "locale": "zh-Hant",
        "tutorial_completed": False,
    }


def load_preferences(project_root: Path) -> dict[str, Any]:
    path = _preferences_path(project_root)
    if not path.exists():
        return default_preferences()
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise LocalizationError("UI preferences are not valid JSON") from exc
    if not isinstance(payload, dict) or payload.get("schema") != UI_PREFERENCES_SCHEMA:
        raise LocalizationError("UI preferences use an unsupported schema")
    if set(payload) != {"schema", "locale", "tutorial_completed"}:
        raise LocalizationError("UI preferences contain unsupported fields")
    if payload.get("locale") not in SUPPORTED_LOCALES:
        raise LocalizationError("UI preferences contain an unsupported locale")
    if not isinstance(payload.get("tutorial_completed"), bool):
        raise LocalizationError("tutorial completion must be a boolean")
    return dict(payload)


def save_preferences(
    project_root: Path,
    *,
    locale: str,
    tutorial_completed: bool,
) -> dict[str, Any]:
    if locale not in SUPPORTED_LOCALES:
        raise LocalizationError("unsupported UI locale")
    payload = {
        "schema": UI_PREFERENCES_SCHEMA,
        "locale": locale,
        "tutorial_completed": bool(tutorial_completed),
    }
    _atomic_write(_preferences_path(project_root), payload)
    return payload


def translate(locale: str, key: str) -> str:
    selected = locale if locale in SUPPORTED_LOCALES else "en"
    if key in _CATALOG[selected]:
        return _CATALOG[selected][key]
    if key in _CATALOG["en"]:
        return _CATALOG["en"][key]
    raise LocalizationError(f"unknown UI string: {key}")
