"""Small, persistent desktop localization and first-run preference store."""

from __future__ import annotations

import json
import os
import secrets
from pathlib import Path
from typing import Any, Mapping


UI_PREFERENCES_SCHEMA = "peerbridge.ui-preferences.v1"
SUPPORTED_LOCALES = ("zh-Hant", "zh-Hans", "en")
LOCALE_LABELS = {
    "zh-Hant": "繁體中文",
    "zh-Hans": "简体中文",
    "en": "English",
}
LABEL_LOCALES = {label: locale for locale, label in LOCALE_LABELS.items()}


class LocalizationError(ValueError):
    """Desktop language preferences or a catalog lookup are invalid."""


_CATALOG: dict[str, dict[str, str]] = {
    "zh-Hant": {
        "nav.chat": "01  對話",
        "nav.work": "02  工作板",
        "nav.review": "03  互評",
        "nav.change": "04  變更",
        "nav.audit": "05  審計",
        "nav.connect": "06  接入",
        "nav.memory": "07  記憶",
        "nav.feedback": "08  意見回饋",
        "nav.announcement": "09  公告",
        "page.chat": "對話",
        "page.work": "工作板",
        "page.review": "互評",
        "page.change": "變更",
        "page.audit": "審計",
        "page.connect": "安全接入",
        "page.memory": "共享記憶",
        "page.feedback": "意見回饋",
        "page.announcement": "公告",
        "toolbar.search": "搜尋",
        "toolbar.pause": "|| 暫停",
        "toolbar.refresh": ">> 刷新",
        "toolbar.refreshing": "正在刷新...",
        "toolbar.refreshed": "已刷新 {time}",
        "toolbar.refresh_failed": "刷新失敗",
        "toolbar.help": "? 教學",
        "toolbar.announcements": "公告",
        "toolbar.announcements_unread": "公告 ({count})",
        "toolbar.updates": "檢查更新",
        "chat.attach": "+ 附件",
        "chat.clear_attachments": "清除附件",
        "chat.no_attachments": "未附加檔案",
        "chat.attachments_selected": "已選取 {count} 個附件；送出後以內容 SHA 安全命名。",
        "chat.attachment_note": "附件會以雜湊副本保存；模型能否直接理解圖片取決於 Provider。",
        "chat.new_room": "+ 新房間",
        "chat.join_control": "+ 加入控制",
        "chat.older": "< 較舊",
        "chat.latest": "最新 >",
        "chat.focus": "⛶ 全屏對話",
        "chat.exit_focus": "退出全屏",
        "chat.auto": "自動",
        "chat.mode.off": "關閉自動回覆",
        "chat.mode.once": "每個 Agent 回覆一輪",
        "chat.mode.discussion": "有限持續討論",
        "chat.rounds": "回合",
        "chat.messages": "訊息",
        "chat.stagnation": "停滯",
        "chat.apply": "套用",
        "chat.pause": "暫停",
        "chat.resume": "恢復",
        "chat.continue": "繼續",
        "chat.stop": "停止",
        "chat.room_seats": "房間席位",
        "chat.apply_seat": "+ 套用席位",
        "chat.remove_seat": "- 移除",
        "chat.manage_providers": "06 接入",
        "chat.send": ">> MCP 送出",
        "chat.message_hint": "Enter 送出 / Shift+Enter 換行",
        "chat.join_to_send": "你尚未加入此房間。請按「+ 加入控制」加入 human-operator 席位後再送出。",
        "chat.seat_hint": "選擇 Global Agent，再加入目前房間。",
        "chat.recipient.all": "全體 Agent (*)",
        "chat.route.direct": "Agent 預設 Route",
        "chat.route.broadcast": "房間席位已指定的模型",
        "chat.route.unregistered": "未登記來源（到 06 接入）",
        "chat.route_unique_required": "找不到唯一 Route；請重新選擇 Provider、模型與思考強度。",
        "chat.model.default": "Provider 預設模型",
        "chat.reasoning.default": "Provider 預設思考",
        "chat.lobby_hint": "Lobby 預設包含 Global Library Agent；拖出會建立可稽核的接收停用記錄。",
        "provider.display_name_required": "DISPLAY NAME 不可留空。",
        "provider.class_invalid": "CLASS 必須是 official、relay 或 local。",
        "provider.endpoint_required": "ENDPOINT 不可留空。",
        "provider.local_loopback_only": "LOCAL Provider 只允許 loopback endpoint。",
        "provider.api_key_required": "OFFICIAL 與 RELAY Provider 必須提供 API KEY。",
        "provider.saving": "正在安全儲存 Provider descriptor，然後經 MCP 登記 SHA 綁定 metadata...",
        "provider.save_failed": "Provider 驗證或 MCP 登記未完成；輸入已清空；credential descriptor 可能已保存。{error}",
        "feedback.prompt": "一句話描述問題",
        "feedback.contact": "回覆電郵（可選）",
        "feedback.attach": "+ 附加畫面／診斷檔",
        "feedback.clear": "清除",
        "feedback.include_key": "附加完整 API Key／Token（只在本機以支援公鑰加密）",
        "feedback.privacy": "普通診斷遮蔽秘密但保留解析結構；完整 Key 不寫入報告、日誌或遙測。",
        "feedback.recipient": "收件者",
        "feedback.destination": "目的地",
        "feedback.key_fingerprint": "公鑰 SHA-256",
        "feedback.privacy_url": "隱私政策",
        "feedback.send": ">> 私密送出",
        "announcement.popup": "收到新公告時彈出通知",
        "announcement.sync": "立即同步",
        "announcement.disabled": "公告服務尚未設定；可在此頁查看已保存公告。",
        "announcement.checking": "正在背景同步公告…",
        "announcement.none": "目前沒有新公告。",
        "announcement.updated": "已同步 {count} 則新公告。",
        "announcement.error": "公告同步失敗：{error}",
        "announcement.severity": "級別",
        "announcement.title": "標題",
        "announcement.published": "發布時間",
        "announcement.popup_title": "PeerBridge 新公告",
        "announcement.open": "開啟公告欄",
        "tutorial.title": "PeerBridge 快速開始",
        "tutorial.next": "下一步",
        "tutorial.back": "上一步",
        "tutorial.done": "完成",
        "tutorial.skip": "略過",
        "tutorial.step1.title": "1 / 4  建立 Agent 接入",
        "tutorial.step1.body": "到「06 接入」新增官方、轉接或本機 Provider。官方與轉接密鑰只放入本機秘密儲存區；本機 Provider 只接受 loopback endpoint 且不需要 API key。",
        "tutorial.step2.title": "2 / 4  將 Agent 加入房間",
        "tutorial.step2.body": "在左側 Global Agent Library 選取 Agent，再拖進房間或用加入按鈕。每個房間席位可獨立選 Provider、模型與思考強度。",
        "tutorial.step3.title": "3 / 4  選擇協作方式",
        "tutorial.step3.body": "Off 只記錄；Once 平行喚醒房內 Agent 一輪；Discussion 在回合、訊息與停滯上限內討論，避免無限回覆。",
        "tutorial.step4.title": "4 / 4  查看證據與回饋",
        "tutorial.step4.body": "工作、互評、變更與審計頁保留協作痕跡。遇到問題可用「08 意見回饋」一次送出診斷；完整 Key 只會在明確勾選後本機加密。",
        "updates.checking": "正在只讀檢查 GitHub Release…",
        "updates.current": "目前已是最新版 v{version}",
        "updates.available": "有新 Alpha v{version}；不會自動下載或安裝。",
        "updates.error": "更新檢查失敗：{error}",
    },
    "zh-Hans": {
        "nav.chat": "01  对话",
        "nav.work": "02  工作板",
        "nav.review": "03  互评",
        "nav.change": "04  变更",
        "nav.audit": "05  审计",
        "nav.connect": "06  接入",
        "nav.memory": "07  记忆",
        "nav.feedback": "08  意见反馈",
        "nav.announcement": "09  公告",
        "page.chat": "对话",
        "page.work": "工作板",
        "page.review": "互评",
        "page.change": "变更",
        "page.audit": "审计",
        "page.connect": "安全接入",
        "page.memory": "共享记忆",
        "page.feedback": "意见反馈",
        "page.announcement": "公告",
        "toolbar.search": "搜索",
        "toolbar.pause": "|| 暂停",
        "toolbar.refresh": ">> 刷新",
        "toolbar.refreshing": "正在刷新...",
        "toolbar.refreshed": "已刷新 {time}",
        "toolbar.refresh_failed": "刷新失败",
        "toolbar.help": "? 教程",
        "toolbar.announcements": "公告",
        "toolbar.announcements_unread": "公告 ({count})",
        "toolbar.updates": "检查更新",
        "chat.attach": "+ 附件",
        "chat.clear_attachments": "清除附件",
        "chat.no_attachments": "未附加文件",
        "chat.attachments_selected": "已选择 {count} 个附件；发送后以内容 SHA 安全命名。",
        "chat.attachment_note": "附件以哈希副本保存；模型能否直接理解图片取决于 Provider。",
        "chat.new_room": "+ 新房间",
        "chat.join_control": "+ 加入控制",
        "chat.older": "< 较早",
        "chat.latest": "最新 >",
        "chat.focus": "⛶ 全屏对话",
        "chat.exit_focus": "退出全屏",
        "chat.auto": "自动",
        "chat.mode.off": "关闭自动回复",
        "chat.mode.once": "每个 Agent 回复一轮",
        "chat.mode.discussion": "有限持续讨论",
        "chat.rounds": "回合",
        "chat.messages": "消息",
        "chat.stagnation": "停滞",
        "chat.apply": "应用",
        "chat.pause": "暂停",
        "chat.resume": "恢复",
        "chat.continue": "继续",
        "chat.stop": "停止",
        "chat.room_seats": "房间席位",
        "chat.apply_seat": "+ 应用席位",
        "chat.remove_seat": "- 移除",
        "chat.manage_providers": "06 接入",
        "chat.send": ">> MCP 发送",
        "chat.message_hint": "Enter 发送 / Shift+Enter 换行",
        "chat.join_to_send": "你尚未加入此房间。请按“+ 加入控制”加入 human-operator 席位后再发送。",
        "chat.seat_hint": "选择 Global Agent，再加入当前房间。",
        "chat.recipient.all": "全体 Agent (*)",
        "chat.route.direct": "Agent 默认 Route",
        "chat.route.broadcast": "房间席位已指定的模型",
        "chat.route.unregistered": "未登记来源（到 06 接入）",
        "chat.route_unique_required": "找不到唯一 Route；请重新选择 Provider、模型与思考强度。",
        "chat.model.default": "Provider 默认模型",
        "chat.reasoning.default": "Provider 默认思考",
        "chat.lobby_hint": "Lobby 默认包含 Global Library Agent；拖出会建立可审计的接收停用记录。",
        "provider.display_name_required": "DISPLAY NAME 不可留空。",
        "provider.class_invalid": "CLASS 必须是 official、relay 或 local。",
        "provider.endpoint_required": "ENDPOINT 不可留空。",
        "provider.local_loopback_only": "LOCAL Provider 仅允许 loopback endpoint。",
        "provider.api_key_required": "OFFICIAL 与 RELAY Provider 必须提供 API KEY。",
        "provider.saving": "正在安全保存 Provider descriptor，然后经 MCP 登记 SHA 绑定 metadata...",
        "provider.save_failed": "Provider 验证或 MCP 登记未完成；输入已清空；credential descriptor 可能已保存。{error}",
        "feedback.prompt": "一句话描述问题",
        "feedback.contact": "回复邮箱（可选）",
        "feedback.attach": "+ 附加画面／诊断文件",
        "feedback.clear": "清除",
        "feedback.include_key": "附加完整 API Key／Token（仅在本机用支持公钥加密）",
        "feedback.privacy": "普通诊断会遮蔽秘密但保留解析结构；完整 Key 不写入报告、日志或遥测。",
        "feedback.recipient": "收件人",
        "feedback.destination": "目的地",
        "feedback.key_fingerprint": "公钥 SHA-256",
        "feedback.privacy_url": "隐私政策",
        "feedback.send": ">> 私密发送",
        "announcement.popup": "收到新公告时弹出通知",
        "announcement.sync": "立即同步",
        "announcement.disabled": "公告服务尚未设置；可在此页查看已保存公告。",
        "announcement.checking": "正在后台同步公告…",
        "announcement.none": "当前没有新公告。",
        "announcement.updated": "已同步 {count} 条新公告。",
        "announcement.error": "公告同步失败：{error}",
        "announcement.severity": "级别",
        "announcement.title": "标题",
        "announcement.published": "发布时间",
        "announcement.popup_title": "PeerBridge 新公告",
        "announcement.open": "打开公告栏",
        "tutorial.title": "PeerBridge 快速开始",
        "tutorial.next": "下一步",
        "tutorial.back": "上一步",
        "tutorial.done": "完成",
        "tutorial.skip": "跳过",
        "tutorial.step1.title": "1 / 4  建立 Agent 接入",
        "tutorial.step1.body": "到“06 接入”新增官方、中转或本机 Provider。官方与中转密钥只进入本机秘密存储；本机 Provider 仅接受 loopback endpoint 且不需要 API key。",
        "tutorial.step2.title": "2 / 4  将 Agent 加入房间",
        "tutorial.step2.body": "在左侧 Global Agent Library 选择 Agent，再拖入房间或使用加入按钮。每个房间席位可独立选择 Provider、模型和思考强度。",
        "tutorial.step3.title": "3 / 4  选择协作方式",
        "tutorial.step3.body": "Off 只记录；Once 并行唤醒房内 Agent 一轮；Discussion 在回合、消息和停滞上限内讨论，避免无限回复。",
        "tutorial.step4.title": "4 / 4  查看证据与反馈",
        "tutorial.step4.body": "工作、互评、变更和审计页保留协作痕迹。遇到问题可用“08 意见反馈”一次提交诊断；完整 Key 仅在明确勾选后本机加密。",
        "updates.checking": "正在只读检查 GitHub Release…",
        "updates.current": "当前已是最新版 v{version}",
        "updates.available": "有新 Alpha v{version}；不会自动下载或安装。",
        "updates.error": "更新检查失败：{error}",
    },
    "en": {
        "nav.chat": "01  Chat",
        "nav.work": "02  Work",
        "nav.review": "03  Reviews",
        "nav.change": "04  Changes",
        "nav.audit": "05  Audit",
        "nav.connect": "06  Providers",
        "nav.memory": "07  Memory",
        "nav.feedback": "08  Feedback",
        "nav.announcement": "09  Announcements",
        "page.chat": "Chat",
        "page.work": "Workboard",
        "page.review": "Peer reviews",
        "page.change": "Changes",
        "page.audit": "Audit",
        "page.connect": "Secure providers",
        "page.memory": "Shared memory",
        "page.feedback": "Feedback",
        "page.announcement": "Announcements",
        "toolbar.search": "Search",
        "toolbar.pause": "|| Pause",
        "toolbar.refresh": ">> Refresh",
        "toolbar.refreshing": "Refreshing...",
        "toolbar.refreshed": "Refreshed {time}",
        "toolbar.refresh_failed": "Refresh failed",
        "toolbar.help": "? Tutorial",
        "toolbar.announcements": "Announcements",
        "toolbar.announcements_unread": "Announcements ({count})",
        "toolbar.updates": "Check updates",
        "chat.attach": "+ Attach",
        "chat.clear_attachments": "Clear attachments",
        "chat.no_attachments": "No attachments",
        "chat.attachments_selected": "{count} attachment(s) selected; content SHA names are used after sending.",
        "chat.attachment_note": "Attachments use hashed copies; direct image understanding depends on the provider.",
        "chat.new_room": "+ New room",
        "chat.join_control": "+ Join control",
        "chat.older": "< Older",
        "chat.latest": "Latest >",
        "chat.focus": "⛶ Focus chat",
        "chat.exit_focus": "Exit focus",
        "chat.auto": "Auto",
        "chat.mode.off": "Automation off",
        "chat.mode.once": "One reply per agent",
        "chat.mode.discussion": "Bounded discussion",
        "chat.rounds": "Rounds",
        "chat.messages": "Messages",
        "chat.stagnation": "Stall",
        "chat.apply": "Apply",
        "chat.pause": "Pause",
        "chat.resume": "Resume",
        "chat.continue": "Continue",
        "chat.stop": "Stop",
        "chat.room_seats": "Room seats",
        "chat.apply_seat": "+ Apply seat",
        "chat.remove_seat": "- Remove",
        "chat.manage_providers": "06 Providers",
        "chat.send": ">> Send via MCP",
        "chat.message_hint": "Enter to send / Shift+Enter for newline",
        "chat.join_to_send": "You are not seated in this room. Click '+ Join control' to add the human-operator seat before sending.",
        "chat.seat_hint": "Select a Global Agent, then add it to this room.",
        "chat.recipient.all": "All Agents (*)",
        "chat.route.direct": "Agent default route",
        "chat.route.broadcast": "Models assigned to room seats",
        "chat.route.unregistered": "No registered source (open 06 Providers)",
        "chat.route_unique_required": "No unique route matches this selection. Reselect the provider, model, and reasoning effort.",
        "chat.model.default": "Provider default model",
        "chat.reasoning.default": "Provider default reasoning",
        "chat.lobby_hint": "Lobby includes Global Library Agents by default; dragging one out creates an auditable receive opt-out.",
        "provider.display_name_required": "DISPLAY NAME is required.",
        "provider.class_invalid": "CLASS must be official, relay, or local.",
        "provider.endpoint_required": "ENDPOINT is required.",
        "provider.local_loopback_only": "LOCAL providers accept loopback endpoints only.",
        "provider.api_key_required": "OFFICIAL and RELAY providers require an API KEY.",
        "provider.saving": "Saving the provider descriptor securely, then registering SHA-bound metadata through MCP...",
        "provider.save_failed": "Provider validation or MCP registration did not complete. Inputs were cleared; the credential descriptor may have been saved. {error}",
        "feedback.prompt": "Describe the problem in one message",
        "feedback.contact": "Reply email (optional)",
        "feedback.attach": "+ Attach screenshot / diagnostic",
        "feedback.clear": "Clear",
        "feedback.include_key": "Include full API key/token (encrypted locally to support key)",
        "feedback.privacy": "Normal diagnostics redact secrets but preserve parser structure. Full keys never enter reports, logs, or telemetry.",
        "feedback.recipient": "Recipient",
        "feedback.destination": "Destination",
        "feedback.key_fingerprint": "Public key SHA-256",
        "feedback.privacy_url": "Privacy policy",
        "feedback.send": ">> Send privately",
        "announcement.popup": "Pop up when a new announcement arrives",
        "announcement.sync": "Sync now",
        "announcement.disabled": "Announcement service is not configured. Saved notices remain available here.",
        "announcement.checking": "Syncing announcements in the background...",
        "announcement.none": "There are no new announcements.",
        "announcement.updated": "Synced {count} new announcement(s).",
        "announcement.error": "Announcement sync failed: {error}",
        "announcement.severity": "Severity",
        "announcement.title": "Title",
        "announcement.published": "Published",
        "announcement.popup_title": "New PeerBridge announcement",
        "announcement.open": "Open announcements",
        "tutorial.title": "PeerBridge quick start",
        "tutorial.next": "Next",
        "tutorial.back": "Back",
        "tutorial.done": "Done",
        "tutorial.skip": "Skip",
        "tutorial.step1.title": "1 / 4  Connect agents",
        "tutorial.step1.body": "Use Secure providers to add an official, relay, or local route. Official and relay keys stay in local secret storage; local providers accept loopback endpoints only and need no API key.",
        "tutorial.step2.title": "2 / 4  Add agents to a room",
        "tutorial.step2.body": "Select an agent in the Global Agent Library, then drag it into a room or use Add. Each room seat can choose its own provider, model, and reasoning effort.",
        "tutorial.step3.title": "3 / 4  Choose collaboration mode",
        "tutorial.step3.body": "Off records only; Once wakes room agents for one parallel round; Discussion runs within round, message, and stagnation limits to prevent reply loops.",
        "tutorial.step4.title": "4 / 4  Inspect evidence and send feedback",
        "tutorial.step4.body": "Work, reviews, changes, and audit preserve collaboration evidence. Feedback sends diagnostics once; a full key is encrypted locally only after explicit opt-in.",
        "updates.checking": "Checking GitHub Release metadata (read only)…",
        "updates.current": "This is the latest release, v{version}",
        "updates.available": "New Alpha v{version} is available; nothing will be downloaded or installed automatically.",
        "updates.error": "Update check failed: {error}",
    },
}


def _preferences_path(project_root: Path) -> Path:
    return project_root.resolve() / ".peerbridge" / "ui-preferences.json"


def _atomic_write(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{secrets.token_hex(8)}.tmp")
    temporary.write_text(
        json.dumps(dict(payload), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def default_preferences() -> dict[str, Any]:
    return {
        "schema": UI_PREFERENCES_SCHEMA,
        "locale": "zh-Hant",
        "tutorial_completed": False,
    }


def load_preferences(project_root: Path) -> dict[str, Any]:
    path = _preferences_path(project_root)
    if not path.exists():
        return default_preferences()
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise LocalizationError("UI preferences are not valid JSON") from exc
    if not isinstance(payload, dict) or payload.get("schema") != UI_PREFERENCES_SCHEMA:
        raise LocalizationError("UI preferences use an unsupported schema")
    if set(payload) != {"schema", "locale", "tutorial_completed"}:
        raise LocalizationError("UI preferences contain unsupported fields")
    if payload.get("locale") not in SUPPORTED_LOCALES:
        raise LocalizationError("UI preferences contain an unsupported locale")
    if not isinstance(payload.get("tutorial_completed"), bool):
        raise LocalizationError("tutorial completion must be a boolean")
    return dict(payload)


def save_preferences(
    project_root: Path,
    *,
    locale: str,
    tutorial_completed: bool,
) -> dict[str, Any]:
    if locale not in SUPPORTED_LOCALES:
        raise LocalizationError("unsupported UI locale")
    payload = {
        "schema": UI_PREFERENCES_SCHEMA,
        "locale": locale,
        "tutorial_completed": bool(tutorial_completed),
    }
    _atomic_write(_preferences_path(project_root), payload)
    return payload


def translate(locale: str, key: str) -> str:
    selected = locale if locale in SUPPORTED_LOCALES else "en"
    if key in _CATALOG[selected]:
        return _CATALOG[selected][key]
    if key in _CATALOG["en"]:
        return _CATALOG["en"][key]
    raise LocalizationError(f"unknown UI string: {key}")
